# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Simon Says
description: The weblog of Simon Woodside.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://simonwoodside.com" # the base hostname & protocol for your site
twitter_username: Simon_Woodside

# Pagination
pagination:
  enabled: true
  per_page: 10
  sort_reverse: true
  trail: 
    before: 3 # The number of links before the current page
    after: 3  # The number of links after the current page

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate-v2
